### ISSUE TITLE
default-gemsファイルの生成に失敗する

### ISSUE THREAD

**Issue by iyuuya** [k0kubun/itamae-plugin-recipe-rbenv#14]
PR #13 が問題なのかitamaeのfile resourceが問題なのか分からなかったのでとりあえず報告だけしておきます。
(file resourceの問題じゃねーのと思ってます。)

[lib/itamae/plugin/recipe/rbenv/install.rb](https://github.com/k0kubun/itamae-plugin-recipe-rbenv/blob/644e6a0cfe08118da74ad2afd84983701e254a21/lib/itamae/plugin/recipe/rbenv/install.rb#L40)
```ruby
if node[:'rbenv-default-gems'] && node[:'rbenv-default-gems'][:'default-gems']
  node[:'rbenv-default-gems'][:install] = true
  file "#{rbenv_root}/default-gems" do
    content node[:'rbenv-default-gems'][:'default-gems'].join("\n") + "\n"
    mode    '664'
    user node[:rbenv][:user] if node[:rbenv][:user]
  end
end
```

file resourceは`/tmp/itamae_tmp/`以下でファイル生成作業をするみたいなんですが、
`user`と`mode`を指定しているとき、ユーザーが`/tmp/itamae_tmp/xxx`の権限を持っておらずパーミッションエラーになるみたいです。

ex)
```
ERROR : stdout | chmod: changing permissions of `/tmp/itamae_tmp/1463378758.00454': Operation not permitted
ERROR : Command `sudo -H -u app -- /bin/sh -c cd\ \~app\ \;\ chmod\ 0600\ /tmp/itamae_tmp/1463378758.00454` failed. (exit status: 1)
ERROR : file[/home/app/.rbenv/default-gems] Failed.
```

`owner`/`group`を指定すれば解決できそうです。

https://github.com/iyuuya/itamae-plugin-recipe-rbenv/commit/a03afdd3e8c314a0dae63a5955a3de908a3c934f
```ruby
if node[:'rbenv-default-gems'] && node[:'rbenv-default-gems'][:'default-gems']
  node[:'rbenv-default-gems'][:install] = true
  file "#{rbenv_root}/default-gems" do
    content node[:'rbenv-default-gems'][:'default-gems'].join("\n") + "\n"
    mode    '664'
    if node[:rbenv][:user]
      owner node[:rbenv][:user]
      group node[:rbenv][:group] || node[:rbenv][:user]
    end
  end
end
```

**Comment by mozamimy** [comment]
@k0kubun ping
わたしもこの問題にハマって、とりあえず fork してしのいだんですが、オフィシャルに対応してもらえるとな〜という気持ちです。

**Comment by k0kubun** [comment]
あー多分一回このissue見て忘れてました。とりいそぎ https://github.com/iyuuya/itamae-plugin-recipe-rbenv/commit/a03afdd3e8c314a0dae63a5955a3de908a3c934f をいれてリリースしました

**Comment by mozamimy** [comment]
ありがとうございます！
